-define(NO_EVENTS,
        [{{<<"module_1">>, attempt, 1},
          {clause,
           [{var,'_'}],
           [],
           [{'case',
             {tuple,[]},
             [{clause,
               [{tuple,[]}],
               [],
               [{'case',
                 {tuple,[]},
                 [{clause,
                   [{tuple,[]}],
                   [],
                   [{tuple,[{atom,return},{atom,ok}]}]}]}]}]}]}}]).

-define(TERMINAL_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           []}}]).

-define(ACTION_REACTION,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{call,
             {remote,{atom,egre},{atom,attempt}},
             [{call,{atom,self},[]},
              {tuple,
               [{var,'Character'},
                {atom,unreserve},
                {var,'Resource'},
                {atom,for},
                {var,'Owner'}]}]},
            {call,
             {remote,{atom,egre},{atom,attempt}},
             [{call,{atom,self},[]},
              {tuple,
               [{var,'Animal'},
                {atom, make_noise}]},
              {atom, false}
             ]}
           ]}}]).

-define(RESEND_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,resend},
                 {var,'Object'},
                 {tuple, [{var, 'Character'},
                          {atom, go},
                          {var, 'Direction'}]}]}}]
            }]}}]).

-define(RESEND_VARIABLE_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{match,
             {var,'Event'},
             {tuple, [{var, 'Character'},
                      {atom, go},
                      {var, 'Direction'}]}},
            {record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,resend},
                 {var,'Object'},
                 {var,'Event'}]}}]
            }]}}]).

-define(MODIFY_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,event},
               {tuple,
                [{var, 'Character'},
                 {atom, go},
                 {var, 'Direction'}]}}]}]
          }}]).

-define(BROADCAST_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Character'},
                          {atom, go},
                          {var, 'Direction'}]}]}}]
            }]}}]).

-define(TYPE_INFERENCE,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var, 'Pid1'},
                {atom, abc},
                {var, 'Pid2'},
                {atom, def},
                {var, 'NotPid'}]},
              {var,'_Context'}]}],
           [{op, '==', {var, 'Pid1'}, {call, {atom, self}, []}},
            {op, '==', {call, {atom, self}, []}, {var, 'Pid2'}}],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Pid1'},
                          {atom, ghi},
                          {var, 'Pid3'},
                          {var, 'NotPid'}]}]}}]
            }]}}]).

-define(SAMPLE_1,
#{{<<"attack_resource">>,attempt,1} =>
      [{clause,
           [{tuple,
                [{map,
                     [{map_field_exact,{atom,character},{var,'Character'}},
                      {map_field_exact,{atom,owner},{var,'Owner'}}]},
                 {var,'Props'},
                 {tuple,
                     [{var,'Character'},
                      {atom,attack},
                      {var,'Target'},
                      {atom,with},
                      {var,'Owner'}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Log'},
                {cons,
                    {tuple,[{atom,event_type},{atom,attack}]},
                    {cons,
                        {tuple,[{atom,event_target},{var,'Target'}]},
                        {nil}}}},
            {record,result,
                [{record_field,{atom,props},{var,'Props'}},
                 {record_field,{atom,log},{var,'Log'}}]}]},
       {clause,
           [{tuple,
                [{map,[{map_field_exact,{atom,character},{var,'Character'}}]},
                 {var,'Props'},
                 {tuple,
                     [{atom,move},
                      {var,'Character'},
                      {var,'From'},
                      {var,'To'},
                      {var,'Exit'}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Log'},
                {cons,
                    {tuple,[{atom,event_type},{atom,move}]},
                    {cons,
                        {tuple,[{atom,from},{var,'From'}]},
                        {cons,
                            {tuple,[{atom,to},{var,'To'}]},
                            {cons,
                                {tuple,[{atom,exit},{var,'Exit'}]},
                                {nil}}}}}},
            {record,result,
                [{record_field,{atom,props},{var,'Props'}},
                 {record_field,{atom,log},{var,'Log'}}]}]},
       {clause,
           [{tuple,
                [{map,[{map_field_exact,{atom,character},{var,'Character'}}]},
                 {var,'Props'},
                 {tuple,[{var,'Character'},{atom,die}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Log'},
                {cons,{tuple,[{atom,event_type},{atom,die}]},{nil}}},
            {record,result,
                [{record_field,{atom,props},{var,'Props'}},
                 {record_field,{atom,log},{var,'Log'}}]}]},
       {clause,[{var,'_'}],[],[{atom,undefined}]}],
  {<<"attack_resource">>,succeed,1} =>
      [{clause,
           [{tuple,
                [{var,'Props'},
                 {tuple,
                     [{var,'Character'},
                      {atom,attack},
                      {var,'Target'},
                      {atom,with},
                      {var,'Owner'}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Resources'},
                {call,
                    {remote,{atom,proplists},{atom,get_value}},
                    [{atom,resources},{var,'Props'},{nil}]}},
            {lc,{call,
                    {atom,reserve},
                    [{var,'Character'},
                     {var,'Resource'},
                     {var,'Amount'},
                     {var,'Owner'}]},
                [{generate,
                     {tuple,[{var,'Resource'},{var,'Amount'}]},
                     {var,'Resources'}}]},
            {match,
                {var,'Log'},
                {cons,
                    {tuple,[{atom,event_type},{atom,attack}]},
                    {cons,
                        {tuple,[{atom,event_target},{var,'Target'}]},
                        {nil}}}},
            {tuple,[{var,'Props'},{var,'Log'}]}]},
       {clause,
           [{tuple,
                [{var,'Props'},
                 {tuple,
                     [{var,'Character'},
                      {atom,move},
                      {var,'From'},
                      {var,'To'},
                      {var,'Exit'}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Owner'},
                {call,
                    {remote,{atom,proplists},{atom,get_value}},
                    [{atom,owner},{var,'Props'}]}},
            {lc,{call,
                    {atom,unreserve},
                    [{var,'Character'},{var,'Resource'},{var,'Owner'}]},
                [{generate,
                     {tuple,[{atom,resource},{var,'Resource'}]},
                     {var,'Props'}}]},
            {match,
                {var,'Log'},
                {cons,
                    {tuple,[{atom,event_type},{atom,move}]},
                    {cons,
                        {tuple,[{atom,from},{var,'From'}]},
                        {cons,
                            {tuple,[{atom,to},{var,'To'}]},
                            {cons,
                                {tuple,[{atom,exit},{var,'Exit'}]},
                                {nil}}}}}},
            {tuple,[{var,'Props'},{var,'Log'}]}]},
       {clause,
           [{tuple,
                [{var,'Props'},
                 {tuple,[{var,'Character'},{atom,die}]},
                 {var,'_'}]}],
           [],
           [{match,
                {var,'Owner'},
                {call,
                    {remote,{atom,proplists},{atom,get_value}},
                    [{atom,owner},{var,'Props'}]}},
            {'case',
                {tuple,[{var,'Character'},{var,'Owner'},{var,'Props'}]},
                [{clause,
                     [{tuple,[{var,'Character'},{var,'Owner'},{var,'Props'}]}],
                     [[{call,{atom,is_list},[{var,'Props'}]}]],
                     [{lc,{call,
                              {atom,unreserve},
                              [{var,'Character'},
                               {var,'Resource'},
                               {var,'Owner'}]},
                          [{generate,
                               {tuple,[{atom,resource},{var,'Resource'}]},
                               {var,'Props'}}]}]},
                 {clause,
                     [{tuple,
                          [{var,'Character'},{var,'Resource'},{var,'Owner'}]}],
                     [],
                     [{call,
                          {remote,{atom,egre},{atom,attempt}},
                          [{call,{atom,self},[]},
                           {tuple,
                               [{var,'Character'},
                                {atom,unreserve},
                                {var,'Resource'},
                                {atom,for},
                                {var,'Owner'}]}]}]}]},
            {match,
                {var,'Log'},
                {cons,{tuple,[{atom,event_type},{atom,die}]},{nil}}},
            {tuple,[{var,'Props'},{var,'Log'}]}]},
       {clause,[{var,'_'}],[],[{atom,undefined}]}]}).
