-define(NO_EVENTS,
        [{{<<"module_1">>, attempt, 1},
          {clause,
           [{var,'_'}],
           [],
           [{'case',
             {tuple,[]},
             [{clause,
               [{tuple,[]}],
               [],
               [{'case',
                 {tuple,[]},
                 [{clause,
                   [{tuple,[]}],
                   [],
                   [{tuple,[{atom,return},{atom,ok}]}]}]}]}]}]}}]).

-define(TERMINAL_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           []}}]).

-define(ACTION_REACTION,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{call,
             {remote,{atom,egre},{atom,attempt}},
             [{call,{atom,self},[]},
              {tuple,
               [{var,'Character'},
                {atom,unreserve},
                {var,'Resource'},
                {atom,for},
                {var,'Owner'}]}]},
            {call,
             {remote,{atom,egre},{atom,attempt}},
             [{call,{atom,self},[]},
              {tuple,
               [{var,'Animal'},
                {atom, make_noise}]},
              {atom, false}
             ]}
           ]}}]).

-define(RESEND_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,resend},
                 {var,'Object'},
                 {tuple, [{var, 'Character'},
                          {atom, go},
                          {var, 'Direction'}]}]}}]
            }]}}]).

-define(RESEND_VARIABLE_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{match,
             {var,'Event'},
             {tuple, [{var, 'Character'},
                      {atom, go},
                      {var, 'Direction'}]}},
            {record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,resend},
                 {var,'Object'},
                 {var,'Event'}]}}]
            }]}}]).

-define(MODIFY_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,event},
               {tuple,
                [{var, 'Character'},
                 {atom, go},
                 {var, 'Direction'}]}}]}]
          }}]).

-define(BROADCAST_RAW_EVENT,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var,'Character'},
                {atom,attack},
                {var,'Target'},
                {atom,with},
                {var,'Owner'}]},
              {var,'_Context'}]}],
           [],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Character'},
                          {atom, go},
                          {var, 'Direction'}]}]}}]
            }]}}]).

-define(TYPE_INFERENCE_SELF,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var, 'Pid1'},
                {atom, abc},
                {var, 'Pid2'},
                {atom, def},
                {var, 'NotPid'}]},
              {var,'_Context'}]}],
           [{op, '==', {var, 'Pid1'}, {call, {atom, self}, []}},
            {op, '==', {call, {atom, self}, []}, {var, 'Pid2'}}],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Pid1'},
                          {atom, ghi},
                          {var, 'Pid3'},
                          {var, 'NotPid'}]}]}}]
            }]}}]).

-define(TYPE_INFERENCE_IS_PID,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var, 'Pid1'}]},
              {var,'_Context'}]}],
           [{call, {atom, is_pid}, [{var, 'Pid1'}]}],
           [{record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Pid1'},
                          {var, 'NotPid'}]}]}}]
            }]}}]).

-define(TYPE_INFERENCE_EQUALS,
        [{{<<"attack_resource">>,attempt,1},
          {clause,
           [{tuple,
             [{var, '_Map'},
              {var,'_Props'},
              {tuple,
               [{var, 'Atom1'},
                {var, 'Int1'},
                {var, 'Float1'},
                {var, 'Char1'},
                {var, 'EmptyList1'}]},
              {var,'_Context'}]}],
           [{op, '==', {var, 'Atom1'}, {atom, atom}},
            {op, '==', {var, 'Int1'}, {integer, 1}},
            {op, '==', {var, 'Float1'}, {float, 1.0}},
            {op, '==', {var, 'Char1'}, {char, $c}},
            {op, '==', {var, 'EmptyList1'}, {nil}}],
           [{match, {var, 'Atom2'}, {var, 'Atom1'}},
            {match, {var, 'Int2'}, {var, 'Int1'}},
            {match, {var, 'Float2'}, {var, 'Float1'}},
            {match, {var, 'Char2'}, {var, 'Char1'}},
            {match, {var, 'EmptyList2'}, {var, 'EmptyList1'}},
            {record, result,
             [{record_field,
               {atom,result},
               {tuple,
                [{atom,broadcast},
                 {tuple, [{var, 'Atom2'},
                          {var, 'Int2'},
                          {var, 'Float2'},
                          {var, 'Char2'},
                          {var, 'EmptyList2'}]}]}}]
            }]}}]).
